# Generated by Django 5.2.6 on 2025-10-01 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published',
            new_name='is_archived',
        ),
    ]
