# Generated by Django 5.2.6 on 2025-10-05 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='follower_user_id',
            new_name='follower_user',
        ),
        migrations.RenameField(
            model_name='following',
            old_name='following_user_id',
            new_name='following_user',
        ),
    ]
