# Generated by Django 5.2.6 on 2025-11-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_follow_followrequest_delete_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected'), (3, 'Revoked')], default=0),
        ),
    ]
