# Generated by Django 5.2.6 on 2025-11-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_followrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='users/profile_images/profile.jpg', upload_to='users/profile_images'),
        ),
    ]
