# Generated by Django 5.2.6 on 2025-12-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all', models.PositiveBigIntegerField()),
                ('public', models.PositiveBigIntegerField()),
                ('private', models.PositiveBigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
